@php
    $tajawalRegular = base64_encode(file_get_contents(public_path('fonts/tajawal/Tajawal-Regular.ttf')));
    $tajawalBold = base64_encode(file_get_contents(public_path('fonts/tajawal/Tajawal-Bold.ttf')));
@endphp
<!DOCTYPE html>
<html lang="{{ session('ui_locale', 'ar') === 'en' ? 'en' : 'ar' }}" dir="{{ session('ui_locale', 'ar') === 'en' ? 'ltr' : 'rtl' }}">
<head>
<meta charset="utf-8">
<style>
    @font-face{font-family:Tajawal;src:url("data:font/ttf;base64,{{ $tajawalRegular }}") format("truetype");font-style:normal;font-weight:400}
    @font-face{font-family:Tajawal;src:url("data:font/ttf;base64,{{ $tajawalBold }}") format("truetype");font-style:normal;font-weight:700}
    @page{margin:0;size:A4}*{box-sizing:border-box}body{margin:0;font-family:Tajawal,sans-serif;color:#172033}
    .cv-sheet{position:relative;width:210mm;min-height:297mm;background:#fff;overflow:hidden}.cv-layout{display:block;width:100%}
    .cv-side{position:fixed;top:0;bottom:0;width:31%;padding:11mm 7mm;background:#456f9f;color:#fff}.cv-main{width:69%;padding:12mm 10mm}
    .cv-sheet[dir=rtl] .cv-side{right:0}.cv-sheet[dir=rtl] .cv-main{margin-right:31%}.cv-sheet[dir=ltr] .cv-side{left:0}.cv-sheet[dir=ltr] .cv-main{margin-left:31%}
    .cv-profile{text-align:center;margin-bottom:7mm}.cv-photo{display:inline-block;width:36mm;height:36mm;border-radius:50%;object-fit:cover;border:1.3mm solid #fff;background:#dbeafe;color:#456f9f;text-align:center;font-size:28pt;font-weight:bold;line-height:36mm}
    .cv-personal-identity{margin:0 0 5mm;text-align:center;color:inherit;word-wrap:break-word}.cv-personal-identity h1{margin:0;color:inherit;font-size:16pt;line-height:1.4}.cv-personal-identity .cv-job{margin-top:1mm;color:inherit;font-size:10pt;line-height:1.5}
    .cv-heading{padding-bottom:6mm;margin-bottom:6mm;border-bottom:.5mm solid #d9dee5}.cv-heading h1{margin:0;color:#172033;font-size:25pt;line-height:1.35}.cv-job{margin-top:2mm;color:#456f9f;font-size:14pt;font-weight:bold}
    .cv-section{page-break-inside:avoid;margin:0 0 6mm}.cv-section h3{margin:0 0 3mm;color:#243449;font-size:13pt;font-weight:bold}.cv-section-mark{display:inline-block;width:4mm;height:4mm;margin:0 0 0 2mm;border:.5mm solid currentColor;border-radius:50%;vertical-align:middle}
    .cv-side .cv-section h3{padding-bottom:2mm;color:#fff;border-bottom:.2mm solid rgba(255,255,255,.4);font-size:12pt}.cv-side .cv-section-mark{display:none}
    .cv-personal-list{display:block}.cv-personal-row{display:block;margin-bottom:3mm}.cv-personal-icon{display:inline-block;width:5mm;height:5mm;margin-left:2mm;border-radius:50%;background:rgba(255,255,255,.15);font-size:6pt;line-height:5mm;text-align:center;vertical-align:top}.cv-personal-row>div{display:inline-block;width:calc(100% - 9mm);vertical-align:top}.cv-personal-row strong{display:block;color:#fff;font-size:8.5pt}.cv-personal-row span:not(.cv-personal-icon){display:block;color:#eef6ff;font-size:9pt;line-height:1.55;word-wrap:break-word;word-break:break-all}
    .cv-personal-row-email span:not(.cv-personal-icon){direction:ltr;text-align:left;font-size:7.5pt;word-wrap:break-word;word-break:break-all}
    .cv-section-items{display:block}.cv-item{position:relative;page-break-inside:avoid;margin-bottom:4mm}.cv-main .cv-item{padding-right:5mm}.cv-sheet[dir=ltr] .cv-main .cv-item{padding-right:0;padding-left:5mm}
    .cv-main .cv-item:before{content:"";position:absolute;right:.5mm;top:2mm;width:2mm;height:2mm;border:.4mm solid #456f9f;border-radius:50%}.cv-sheet[dir=ltr] .cv-main .cv-item:before{right:auto;left:.5mm}
    .cv-item-heading strong{font-size:11.5pt}.cv-item-heading time{float:left;color:#526174;font-size:8.5pt;font-weight:bold}.cv-sheet[dir=ltr] .cv-item-heading time{float:right}
    .cv-organization{display:block;margin-top:.6mm;color:#456f9f;font-size:9.5pt;font-weight:bold}.cv-item-meta{margin-top:1mm;color:#64748b;font-size:8.5pt;line-height:1.5}.cv-item-meta span{display:inline-block;margin-left:3mm}.cv-body{margin-top:1mm;color:#425168;font-size:9.5pt;line-height:1.65;white-space:pre-line;word-wrap:break-word}.cv-side .cv-body{color:#f0f7ff}.cv-link{margin-top:1mm;color:#456f9f;font-size:8pt;word-wrap:break-word}.cv-level{float:left;padding:1mm 2mm;border-radius:4mm;background:rgba(255,255,255,.15);font-size:8pt}
    .content-sparse .cv-heading h1{font-size:31pt}.content-sparse .cv-job{font-size:17pt}.content-sparse .cv-section{margin-bottom:9mm}.content-sparse .cv-section h3{font-size:16pt}.content-sparse .cv-item-heading strong{font-size:13pt}.content-sparse .cv-body{font-size:11pt;line-height:1.85}.content-sparse .cv-personal-row strong,.content-sparse .cv-personal-row span:not(.cv-personal-icon){font-size:10pt}.content-sparse .cv-personal-row-email span:not(.cv-personal-icon){font-size:7.5pt}.content-sparse .cv-personal-identity h1{font-size:19pt}.content-sparse .cv-personal-identity .cv-job{font-size:12pt}.content-dense .cv-side{padding:8mm 5mm}.content-dense .cv-main{padding:9mm 7mm}.content-dense .cv-section{margin-bottom:4mm}.content-dense .cv-item{margin-bottom:2mm}.content-dense .cv-body{font-size:8pt;line-height:1.45}.content-dense .cv-personal-identity h1{font-size:13pt}.content-dense .cv-personal-identity .cv-job{font-size:8pt}

    .template-royal_gold{border:3mm solid #c5a55b;background:#fffdf8}.template-royal_gold .cv-side{position:relative;top:auto;left:auto!important;right:auto!important;bottom:auto;width:100%;min-height:62mm;padding:7mm 9mm;background:#f4ead2;color:#29241d;border-bottom:.5mm solid #c5a55b}.template-royal_gold .cv-profile{float:right;margin:0 0 0 7mm}.template-royal_gold[dir=ltr] .cv-profile{float:left;margin:0 7mm 0 0}.template-royal_gold .cv-photo{width:32mm;height:32mm;line-height:32mm;border-color:#c5a55b;background:#fff;color:#866a2d}.template-royal_gold .cv-personal-section{display:inline-block;width:44%;vertical-align:top}.template-royal_gold .cv-side>.cv-section:not(.cv-personal-section){display:inline-block;width:24%;margin-left:3%;vertical-align:top}.template-royal_gold .cv-side .cv-section h3,.template-royal_gold .cv-personal-row strong,.template-royal_gold .cv-personal-row span:not(.cv-personal-icon),.template-royal_gold .cv-side .cv-body,.template-royal_gold .cv-side .cv-item small{color:#3f3729}.template-royal_gold .cv-personal-row{display:inline-block;width:48%;margin-bottom:2mm}.template-royal_gold .cv-main{width:auto;margin:0 8mm!important;padding:7mm 8mm}.template-royal_gold .cv-heading{text-align:center;border-bottom:1mm double #c5a55b}.template-royal_gold .cv-heading h1{font-family:serif;color:#29241d}.template-royal_gold .cv-job,.template-royal_gold .cv-organization,.template-royal_gold .cv-link{color:#9a7628}.template-royal_gold .cv-main .cv-section h3{text-align:center;color:#73591f}

    .template-midnight_luxury .cv-side{position:relative;left:auto!important;right:auto!important;bottom:auto;width:100%;min-height:58mm;padding:7mm 11mm;background:#07152d;border-bottom:2mm solid #d1aa54}.template-midnight_luxury .cv-profile{float:right;margin:0 0 0 8mm}.template-midnight_luxury[dir=ltr] .cv-profile{float:left;margin:0 8mm 0 0}.template-midnight_luxury .cv-photo{width:35mm;height:35mm;line-height:35mm;border-color:#d1aa54;background:#172a49;color:#d1aa54}.template-midnight_luxury .cv-personal-section{display:inline-block;width:44%;vertical-align:top}.template-midnight_luxury .cv-side>.cv-section:not(.cv-personal-section){display:inline-block;width:24%;margin-left:3%;vertical-align:top}.template-midnight_luxury .cv-personal-row{display:inline-block;width:48%;margin-bottom:2mm}.template-midnight_luxury .cv-main{width:100%;margin:0!important;padding:8mm 14mm}.template-midnight_luxury .cv-heading{text-align:center;border:0}.template-midnight_luxury .cv-heading h1{color:#07152d}.template-midnight_luxury .cv-job,.template-midnight_luxury .cv-organization,.template-midnight_luxury .cv-link{color:#9a772c}.template-midnight_luxury .cv-main .cv-section h3{padding-right:3mm;border-right:1.2mm solid #d1aa54;color:#07152d}

    .template-emerald_signature{background:#f7faf8}.template-emerald_signature .cv-side{left:0!important;right:auto!important;width:34%;padding:13mm 7mm;background:#0b5d4b;border-radius:0 20mm 0 0}.template-emerald_signature .cv-main{width:66%;margin-left:34%!important;margin-right:0!important;padding:13mm 9mm}.template-emerald_signature .cv-photo{border-radius:4mm;border-color:#bde9d8}.template-emerald_signature .cv-heading{border:0}.template-emerald_signature .cv-heading h1{color:#123b33}.template-emerald_signature .cv-job,.template-emerald_signature .cv-organization,.template-emerald_signature .cv-link{color:#0b8065}.template-emerald_signature .cv-main .cv-section{padding:4mm;background:#fff;border:.2mm solid #dcece7;border-radius:3mm}.template-emerald_signature .cv-main .cv-section h3{color:#0b5d4b}

    .template-modern_silk .cv-side{position:relative;left:auto!important;right:auto!important;bottom:auto;width:100%;min-height:54mm;padding:6mm 11mm;background:#f2effc;color:#29224b;border-top:4mm solid #6551a5}.template-modern_silk .cv-profile{float:right;margin:0 0 0 7mm}.template-modern_silk[dir=ltr] .cv-profile{float:left;margin:0 7mm 0 0}.template-modern_silk .cv-photo{width:29mm;height:29mm;line-height:29mm;border-radius:3mm;background:#ddd6fe;color:#6551a5}.template-modern_silk .cv-personal-section{display:inline-block;width:44%;vertical-align:top}.template-modern_silk .cv-side>.cv-section:not(.cv-personal-section){display:inline-block;width:24%;margin-left:3%;vertical-align:top}.template-modern_silk .cv-personal-row{display:inline-block;width:48%;margin-bottom:2mm}.template-modern_silk .cv-side .cv-section h3,.template-modern_silk .cv-personal-row strong,.template-modern_silk .cv-personal-row span:not(.cv-personal-icon),.template-modern_silk .cv-side .cv-body,.template-modern_silk .cv-side .cv-item small{color:#3c355a}.template-modern_silk .cv-personal-icon{background:#6551a5}.template-modern_silk .cv-main{width:100%;margin:0!important;padding:9mm 14mm}.template-modern_silk .cv-heading{border-bottom:2mm solid #6551a5}.template-modern_silk .cv-heading h1{color:#29224b}.template-modern_silk .cv-job,.template-modern_silk .cv-organization,.template-modern_silk .cv-link,.template-modern_silk .cv-main .cv-section h3{color:#6551a5}
    /* Keep exported layouts within one A4 page using geometry supported by Dompdf. */
    .template-royal_gold .cv-layout{padding:0!important}
    .template-royal_gold .cv-side{position:fixed!important;top:3mm!important;bottom:3mm!important;left:auto!important;right:3mm!important;width:22%!important;min-height:0!important;padding:12mm 7mm!important;background:#f4ead2!important;border:0!important;border-left:1mm solid #c5a55b!important}
    .template-royal_gold .cv-main{width:61%!important;margin:0!important;padding:15mm 10mm!important}
    .template-royal_gold .cv-profile{float:none!important;margin:0 0 8mm!important}.template-royal_gold .cv-personal-section,.template-royal_gold .cv-side>.cv-section:not(.cv-personal-section){display:block!important;width:auto!important;margin:0 0 6mm!important}
    .template-royal_gold .cv-personal-row{display:block!important;width:auto!important}.template-royal_gold .cv-heading{text-align:right!important}.template-royal_gold[dir=ltr] .cv-heading{text-align:left!important}.template-royal_gold .cv-heading h1{font-family:Tajawal,sans-serif!important}

    .template-midnight_luxury .cv-layout{padding:0!important}
    .template-midnight_luxury .cv-side{position:fixed!important;top:0!important;bottom:0!important;left:auto!important;right:0!important;width:22%!important;min-height:0!important;padding:15mm 9mm!important;background:#07152d!important;border:0!important;border-right:4mm solid #d1aa54!important}
    .template-midnight_luxury .cv-main{width:56%!important;margin:0!important;padding:18mm 10mm!important}
    .template-midnight_luxury .cv-profile{float:none!important;margin:0 0 9mm!important}.template-midnight_luxury .cv-personal-section,.template-midnight_luxury .cv-side>.cv-section:not(.cv-personal-section){display:block!important;width:auto!important;margin:0 0 7mm!important}
    .template-midnight_luxury .cv-personal-row{display:block!important;width:auto!important}.template-midnight_luxury .cv-heading{text-align:right!important;border-bottom:.7mm solid #d1aa54!important}.template-midnight_luxury[dir=ltr] .cv-heading{text-align:left!important}

    .template-emerald_signature .cv-layout{padding:0!important}.template-emerald_signature .cv-main{width:60%!important;margin:0!important}.template-emerald_signature .cv-side{left:auto!important;right:0!important;width:23%!important}

    .template-modern_silk .cv-layout{padding:0!important}
    .template-modern_silk .cv-side{position:fixed!important;top:0!important;bottom:0!important;left:auto!important;right:0!important;width:16%!important;min-height:0!important;padding:16mm 5mm!important;background:#f2effc!important;border:0!important;border-top:8mm solid #6551a5!important}
    .template-modern_silk .cv-main{width:70%!important;margin:0!important;padding:14mm 11mm!important}
    .template-modern_silk .cv-profile{float:none!important;margin:0 0 8mm!important}.template-modern_silk .cv-personal-section,.template-modern_silk .cv-side>.cv-section:not(.cv-personal-section){display:block!important;width:auto!important;margin:0 0 6mm!important}
    .template-modern_silk .cv-personal-row{display:block!important;width:auto!important}.template-modern_silk .cv-heading{text-align:right!important}.template-modern_silk[dir=ltr] .cv-heading{text-align:left!important}

    .content-sparse .cv-main .cv-section{margin-bottom:17mm}.content-sparse .cv-main .cv-item{margin-bottom:10mm}.content-sparse .cv-main{padding-top:18mm}
    .cv-personal-identity h1.cv-name-long{font-size:12pt!important;line-height:1.4;white-space:nowrap;letter-spacing:-.25pt}.cv-personal-identity h1.cv-name-extra-long{font-size:9pt!important;line-height:1.4;white-space:nowrap;letter-spacing:-.4pt}

    /* Dompdf-compatible bilingual A4 layout. Tables and absolute positioning
       keep the browser design stable while all text remains vector text. */
    .cv-bilingual-sheet{position:relative;display:block;width:210mm;height:296mm;min-height:0!important;background:#fff;overflow:hidden;color:#172033}
    .cv-bilingual-top{position:absolute;top:0;right:0;left:0;display:block;height:38mm;padding:6mm 10mm 5mm 39mm;background:#456f9f;color:#fff}
    .cv-bilingual-photo{position:absolute;top:7mm;left:10mm;display:block;width:25mm;height:25mm;border:1mm solid #fff;border-radius:50%;background:#dbeafe;color:#456f9f;text-align:center;font-size:22pt;font-weight:bold;line-height:25mm}
    .cv-header-personal{display:block;width:100%;color:#fff}.cv-header-personal[dir=rtl]{direction:rtl;text-align:right}.cv-header-personal[dir=ltr]{direction:ltr;text-align:left}.cv-header-personal small{display:block;margin:0 0 1mm;font-size:7pt;font-weight:bold;color:#e9f2fc}.cv-header-personal h1{margin:0;color:#fff;font-size:18pt;line-height:1.25}.cv-header-job{margin-top:.6mm;color:#fff;font-size:9.5pt;font-weight:bold}
    .cv-header-contacts{display:block;margin-top:2.3mm;color:#fff;font-size:6.5pt;line-height:1.45}.cv-header-contacts span{display:inline-block;margin:0 0 1mm 4mm;white-space:nowrap}.cv-header-contacts strong{color:#fff;font-size:inherit}
    .cv-bilingual-columns{position:absolute;top:38mm;right:0;bottom:0;left:0;display:table;width:100%;height:258mm;table-layout:fixed;direction:ltr;border-collapse:collapse}
    .cv-language-column{display:table-cell;width:50%;padding:5mm 6mm;vertical-align:top;color:#172033;overflow:hidden}.cv-language-column[dir=ltr]{direction:ltr;text-align:left;border-right:.35mm solid #cbd5e1;font-family:Tajawal,sans-serif}.cv-language-column[dir=rtl]{direction:rtl;text-align:right}
    .cv-language-column .cv-section{margin:0 0 3.4mm;page-break-inside:avoid}.cv-language-column .cv-section h3{margin:0 0 1.6mm;padding:0 0 1mm;border-bottom:.3mm solid #d9dee5;color:#243449;font-size:9.2pt;line-height:1.35;font-weight:bold}
    .cv-language-column .cv-section-mark{display:inline-block;width:3.2mm;height:3.2mm;margin:0 0 0 1.3mm;border:.4mm solid currentColor;border-radius:50%;vertical-align:middle}.cv-language-column[dir=ltr] .cv-section-mark{margin:0 1.3mm 0 0}
    .cv-language-column .cv-section-items{display:block}.cv-language-column .cv-item{display:block;margin:0 0 2.2mm;page-break-inside:avoid}.cv-language-column .cv-item-heading{display:block;line-height:1.35}.cv-language-column .cv-item-heading strong{font-size:7.4pt;line-height:1.4}.cv-language-column .cv-item-heading time{float:none;display:inline-block;margin:0 2mm;color:#526174;font-size:5.8pt;font-weight:bold}.cv-language-column .cv-level{float:none;display:inline-block;margin:0 1mm;padding:.4mm 1mm;background:#eef2f7;color:#334155;font-size:5.5pt}
    .cv-language-column .cv-organization{display:block;margin-top:.3mm;color:#456f9f;font-size:6.4pt;font-weight:bold}.cv-language-column .cv-item-meta{margin-top:.5mm;color:#64748b;font-size:5.6pt;line-height:1.4}.cv-language-column .cv-item-meta span{display:inline-block;margin:0 0 0 2mm}.cv-language-column .cv-body{margin-top:.7mm;color:#425168;font-size:6.3pt;line-height:1.48;white-space:pre-line;word-wrap:break-word}.cv-language-column .cv-link{margin-top:.5mm;color:#456f9f;font-size:5.5pt;word-wrap:break-word}
    .cv-bilingual-sheet.content-dense .cv-bilingual-top{height:34mm;padding-top:4mm}.cv-bilingual-sheet.content-dense .cv-bilingual-photo{top:5mm;width:23mm;height:23mm;line-height:23mm}.cv-bilingual-sheet.content-dense .cv-bilingual-columns{top:34mm;height:262mm}.cv-bilingual-sheet.content-dense .cv-language-column{padding:3.8mm 5mm}.cv-bilingual-sheet.content-dense .cv-language-column .cv-section{margin-bottom:2mm}.cv-bilingual-sheet.content-dense .cv-language-column .cv-section h3{margin-bottom:1mm;font-size:7.8pt}.cv-bilingual-sheet.content-dense .cv-language-column .cv-item{margin-bottom:1.2mm}.cv-bilingual-sheet.content-dense .cv-language-column .cv-body{font-size:5.3pt;line-height:1.35}.cv-bilingual-sheet.content-dense .cv-language-column .cv-item-heading strong{font-size:6.2pt}
    .cv-bilingual-sheet.template-royal_gold .cv-bilingual-top{background:#9a7628}.cv-bilingual-sheet.template-royal_gold .cv-language-column .cv-organization{color:#9a7628}
    .cv-bilingual-sheet.template-midnight_luxury .cv-bilingual-top{background:#07152d}.cv-bilingual-sheet.template-midnight_luxury .cv-language-column .cv-organization{color:#8a6b28}
    .cv-bilingual-sheet.template-emerald_signature .cv-bilingual-top{background:#0b5d4b}.cv-bilingual-sheet.template-emerald_signature .cv-language-column .cv-organization{color:#0b8065}
    .cv-bilingual-sheet.template-modern_silk .cv-bilingual-top{background:#6551a5}.cv-bilingual-sheet.template-modern_silk .cv-language-column .cv-organization{color:#6551a5}
    .cv-watermark{display:none}
</style>
</head>
<body>@include('resume._document', ['pdfMode' => true, 'paid' => true])</body>
</html>
